version: '3.9'

services:
  frontend:
    container_name: "frontend-dev"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: npm run dev

  backend:
    container_name: "backend-dev"
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    entrypoint: /entrypoint.sh
    command: python manage.py runserver
    volumes:
      - static:/backend/static
      - ./backend:/backend
    depends_on:
      - db

  db:
    container_name: "db-dev"
    image: postgres:13.0-alpine
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  nginx:
    container_name: "nginx-dev"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static:
  node-modules:
